### PR TITLE
feat(eslint-config-angular): use recommendation rules

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by IKatsuba** [comment]
Непонятен профит. Опиши коротко что поменялось

**Comment by splincode** [comment]
@IKatsuba Hello, in JavaScript we have most possible problems in runtime and in TypeScript in compile time )) 

However, we can avoid this thanks to the standard rules that are recommended to be used in the project.

- Eslint 

The current eslint:recommended rules can be found at [github.com/eslint/eslint/blob/master/conf/eslint-recommended.js](https://github.com/eslint/eslint/blob/master/conf/eslint-recommended.js).

- TypeScriptEslint

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended.ts

All these rules are very helpful in detecting critical errors

**Comment by splincode** [comment]
@IKatsuba @SuperOleg39 hello, please review me)

**Review by SuperOleg39 — APPROVED** [review]
LGTM

**Pull request merged**
